### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by YilKanda** [BrightCoders-Proyectos/tribo-web#1]
# REQUIREMENTS
This issue is to generate the Ruby on Rails code base, which will allow to develop the project.

## Rails Version:  6.0.3.4

# Acceptance Criteria
Preferably use the command:

- [x] rails new tribo --database=postgresql --skip-sprockets
- [x] Rubocop setup to filter styling of our code

**Comment by YilKanda** [comment]
We must specify which version of Ruby we are going to use all the members of the project, to avoid compatibility errors. 

The most current version is 2.7.2.

**Comment by edgarjaymez** [comment]
> We must specify which version of Ruby we are going to use all the members of the project, to avoid compatibility errors.
> 
> The most current version is 2.7.2.

Let's define both Ruby and Rails version in the oncoming meet and then write them in the description of this issue
