### ISSUE TITLE
TailwindCSS Setup

### ISSUE THREAD

**Issue by edgarjaymez** [BrightCoders-Proyectos/tribo-web#2]
# REQUIREMENTS
This issue is to include TailwindCSS in the project, which will allow to style the app more easily.

# Acceptance Criteria
Preferably use this command to install Tailwind:
- [x] yarn add tailwindcss@comp (Then select **_v2.0.1 compat_** from the list)

You can use [this tutorial](https://youtu.be/3xcUSIu3nXA) to configure Tailwind with Ruby on Rails

**Comment by YilKanda** [comment]
What would be the difference to install it with yarn?

`yarn add tailwindcss --dev`

**Comment by YilKanda** [comment]
For the css actions to work, could vanillaJS, StimulusJS, etc., be implemented?

In the case of wanting to implement StimulusJS, preferably install it with the command:

`yarn add stimulus `

**Comment by edgarjaymez** [comment]
> What would be the difference to install it with yarn?
> 
> `yarn add tailwindcss --dev`

According to documentation, version 1.9.6 of Tailwind works perfectly with yarn, but in version 2.0.1 yarn is not mentioned even once. 
The `postcss autoprefixer` installations are also necessary for Tailwind to work smoothly in all browsers without writing vendor prefixes  (that's the main reason behind installing autoprefixer)

**Comment by edgarjaymez** [comment]
> For the css actions to work, could vanillaJS, StimulusJS, etc., be implemented?
> 
> In the case of wanting to implement StimulusJS, preferably install it with the command:
> 
> `yarn add stimulus `

Haven't heard of them, if you want to use StimulusJS, feel free to do so

**Comment by YilKanda** [comment]
> According to documentation, version 1.9.6 of Tailwind works perfectly with yarn, but in version 2.0.1 yarn is not mentioned even once.
> The `postcss autoprefixer` installations are also necessary for Tailwind to work smoothly in all browsers without writing vendor prefixes (that's the main reason behind installing autoprefixer)

Postcss autoprefixer installations are done by installing it in yarn with this code:

`yarn add tailwindcss@compat postcss@^7 autoprefixer@^7 postcss-flexbugs-fixes@^4 postcss-preset-env`
