### ISSUE TITLE
Get a Google API Key

### ISSUE THREAD

**Issue by PeterChav01** [BrightCoders-Proyectos/tribo-web#23]
# REQUIREMENTS
Get from BirghtCoders Academy the Google API to add it to the project.

Now we’ll setup rails to use the key. To protect our key let’s use Rails Credentials. 

In terminal run:

`rails credentials:edit`

Add this line at the end:

`google_maps_api_key: INSERT-YOUR-KEY-HERE`

We are now able to access our key in our Rails app through `Rails.application.credentials.google_maps_api_key`

**Comment by cardotrejos** [comment]
Currently I'm working with things related to maps and geolocation. Carlos already give us the API Key

**Comment by YilKanda** [comment]
The API is ready to be assigned to the project.
