### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by EduJimenez96** [BrightCoders-Proyectos/tribo-web#4]
# REQUIREMENTS
As an user I need to config the database, and generate scaffold for each of the models based on the database model.

# Acceptance Criteria
- [x] Config postgresql to use in rails
- [x] Add a Super Admin user
- [x] Generate controllers
- [x] Generate models

**Comment by YilKanda** [comment]
Models and controllers will be created when performing the CRUD. 

_Check that issue._
