### ISSUE TITLE
Heroku Setup

### ISSUE THREAD

**Issue by edgarjaymez** [BrightCoders-Proyectos/tribo-web#5]
# REQUIREMENTS
This issue is to configure the project to be deployed in Heroku Cloud

# Acceptance Criteria
- [x] Give access to Heroku App to all members of this repo

Deploy Rails code base to test Heroku with following commands:
(Using [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli)) 
- [x] heroku login
- [x] heroku git:remote -a bc-tribo
- [x] git push heroku master

**Comment by YilKanda** [comment]
The name of the app on Heroku, why is it called bc-tribo?

**Comment by edgarjaymez** [comment]
> The name of the app on Heroku, why is it called bc-tribo?

Tribo was not available, so my idea was to add bc (Bright Coders) prefix
